version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5001
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.41
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: mymainuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306